### ISSUE TITLE
Can't run on macos with the below error

### ISSUE THREAD

**Issue by medoer** [jwenjian/artline-demo#5]
Traceback (most recent call last):
  File "app.py", line 29, in <module>
    pl.load_pkl()
  File "app.py", line 24, in load_pkl
    learn = load_learner(path, 'ArtLine_650.pkl')
  File "/usr/local/lib/python3.7/site-packages/fastai/basic_train.py", line 621, in load_learner
    state = torch.load(source, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(source)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ArtLine_650.pkl'

**Comment by jwenjian** [comment]
download ArtLine_650.pkl from here (https://github.com/jwenjian/artline-demo/releases/download/v0.1.0/ArtLine_650.pkl) if you cannot reach the dropbox url

**Comment by jwenjian** [comment]
Duplicate of #2
